"""
core.reporter
=============
Collects findings from modules, prints CLI summary, writes JSON + HTML.
"""
import json
import os
from datetime import datetime, timezone


TOOL_NAME = "POSTMaster"
TOOL_VERSION = "1.0"
TOOL_AUTHOR = "jrhackerman"


SEVERITY_RANK = {"info": 0, "low": 1, "medium": 2, "high": 3, "critical": 4}
SEV_COLOR = {
    "info":     "\033[36m",  # cyan
    "low":      "\033[32m",  # green
    "medium":   "\033[33m",  # yellow
    "high":     "\033[35m",  # magenta
    "critical": "\033[31m",  # red
}
RESET = "\033[0m"


class Reporter:
    def __init__(self, target, port):
        self.target = target
        self.port = port
        self.started_at = None
        self.finished_at = None
        self.results = {}  # module_name -> module_result dict

    def start(self):
        self.started_at = datetime.now(timezone.utc).isoformat()

    def finish(self):
        self.finished_at = datetime.now(timezone.utc).isoformat()

    def add(self, module_name, result):
        self.results[module_name] = result

    def all_findings(self):
        out = []
        for mod, res in self.results.items():
            for f in res.get("findings", []):
                f2 = dict(f)
                f2["module"] = mod
                out.append(f2)
        out.sort(key=lambda x: -SEVERITY_RANK.get(x.get("severity", "info"), 0))
        return out

    def to_dict(self):
        return {
            "tool": TOOL_NAME,
            "version": TOOL_VERSION,
            "author": TOOL_AUTHOR,
            "target": self.target,
            "port": self.port,
            "started_at": self.started_at,
            "finished_at": self.finished_at,
            "modules": self.results,
            "findings": self.all_findings(),
        }

    # ---------- output ----------
    def print_summary(self):
        print("\n" + "=" * 72)
        print(f" REPORT  {self.target}:{self.port}")
        print("=" * 72)
        findings = self.all_findings()
        if not findings:
            print(" No findings.")
            return
        counts = {}
        for f in findings:
            counts[f.get("severity", "info")] = counts.get(f.get("severity", "info"), 0) + 1
        order = ["critical", "high", "medium", "low", "info"]
        summary = "  ".join(f"{SEV_COLOR.get(s,'')}{s.upper()}: {counts.get(s,0)}{RESET}"
                            for s in order)
        print(" " + summary)
        print("-" * 72)
        for f in findings:
            sev = f.get("severity", "info")
            color = SEV_COLOR.get(sev, "")
            print(f" [{color}{sev.upper():<8}{RESET}] ({f.get('module')}) "
                  f"{f.get('title')}")
            if f.get("detail"):
                print(f"            {f['detail']}")
        print("=" * 72)

    def write_json(self, path):
        os.makedirs(os.path.dirname(os.path.abspath(path)) or ".", exist_ok=True)
        with open(path, "w") as f:
            json.dump(self.to_dict(), f, indent=2, default=str)

    def write_html(self, path):
        os.makedirs(os.path.dirname(os.path.abspath(path)) or ".", exist_ok=True)
        findings = self.all_findings()
        rows = []
        for f in findings:
            sev = f.get("severity", "info")
            rows.append(
                f"<tr class='sev-{sev}'>"
                f"<td>{sev.upper()}</td>"
                f"<td>{f.get('module','')}</td>"
                f"<td>{_h(f.get('title',''))}</td>"
                f"<td>{_h(f.get('detail',''))}</td>"
                f"</tr>"
            )
        html = f"""<!doctype html>
<html><head><meta charset="utf-8"><title>SMTP Pentest Report — {_h(self.target)}</title>
<style>
 body{{font-family:-apple-system,Segoe UI,Roboto,sans-serif;margin:2rem;background:#0f1115;color:#e6e6e6}}
 h1{{margin-top:0}} table{{border-collapse:collapse;width:100%;margin-top:1rem}}
 th,td{{padding:.5rem .75rem;text-align:left;border-bottom:1px solid #2a2d36;vertical-align:top}}
 th{{background:#1a1d24}}
 tr.sev-critical td:first-child{{color:#ff5252;font-weight:700}}
 tr.sev-high td:first-child{{color:#ff8a3d;font-weight:700}}
 tr.sev-medium td:first-child{{color:#ffd866;font-weight:700}}
 tr.sev-low td:first-child{{color:#7ec699;font-weight:700}}
 tr.sev-info td:first-child{{color:#7fc7ff}}
 .meta{{color:#9aa0a6;font-size:.9rem}}
 .brand{{font-weight:700;color:#7fc7ff}}
 footer{{margin-top:2rem;padding-top:1rem;border-top:1px solid #2a2d36;
        color:#9aa0a6;font-size:.85rem;text-align:center}}
 footer .sig{{color:#7fc7ff;font-weight:700;letter-spacing:.5px}}
</style></head><body>
<h1>SMTP Pentest Report</h1>
<p class="meta">Target: <b>{_h(self.target)}:{self.port}</b><br>
Started: {self.started_at}<br>Finished: {self.finished_at}<br>
Generated by <span class="brand">{TOOL_NAME} v{TOOL_VERSION}</span> &mdash;
by <span class="brand">{TOOL_AUTHOR}</span></p>
<table><thead><tr><th>Severity</th><th>Module</th><th>Finding</th><th>Detail</th></tr></thead>
<tbody>{''.join(rows) or '<tr><td colspan=4>No findings.</td></tr>'}</tbody></table>
<footer>
  Report produced by <span class="sig">{TOOL_NAME} v{TOOL_VERSION}</span> &middot;
  Crafted by <span class="sig">{TOOL_AUTHOR}</span>
</footer>
</body></html>"""
        with open(path, "w") as f:
            f.write(html)


def _h(s):
    return (str(s).replace("&", "&amp;").replace("<", "&lt;")
            .replace(">", "&gt;").replace('"', "&quot;"))
